unit ModflowIdentifiersUnit;

interface

uses
  Classes, ErrorMessages;

var
  PackageIdentifiers: TAnsiStringList;
  ObsIdentifiers: TAnsiStringList;
  BoundaryIdentifiers: TAnsiStringList;

const
  StressPeriodID1 = 'STRESS PERIOD NO. ';
  StressPeriodID2 = 'LENGTH =';
  StartNewTimeStep = 'SOLVING FOR HEAD';
  IterationID1 = 'ITERATIONS FOR TIME STEP';
  IterationID2 = 'IN STRESS PERIOD';
  ArrayID1 = ' IN LAYER ';
  ArrayID2 = ' AT END OF TIME STEP ';
  ArrayID3 = ' FOR CROSS SECTION AT END OF TIME STEP';
  BudgetID = 'VOLUMETRIC BUDGET';
  TimeSummary = 'TIME SUMMARY';

const
  StrHEADANDDRAWDOWNOB = 'HEAD AND DRAWDOWN OBSERVATIONS';


implementation

Procedure InitializePackageIdentifiers;
begin
  PackageIdentifiers := TAnsiStringList.Create;
  PackageIdentifiers.Add('BAS -- BASIC PACKAGE');
  PackageIdentifiers.Add('BCF -- BLOCK-CENTERED FLOW PACKAGE');
  PackageIdentifiers.Add('CHD -- TIME-VARIANT SPECIFIED-HEAD OPTION');
  PackageIdentifiers.Add('DE4 -- D4 DIRECT SOLUTION PACKAGE');
  PackageIdentifiers.Add('DRN -- DRAIN PACKAGE');
  PackageIdentifiers.Add('DRT7 -- DRAIN RETURN PACKAGE');
  PackageIdentifiers.Add('ETS7 -- EVAPOTRANSPIRATION SEGMENTS PACKAGE');
  PackageIdentifiers.Add('EVT -- EVAPOTRANSPIRATION PACKAGE');
  PackageIdentifiers.Add('FHB1 -- SPECIFIED FLOW PACKAGE');
  PackageIdentifiers.Add('GAGING STATION');
  PackageIdentifiers.Add('GHB -- GENERAL-HEAD BOUNDARY PACKAGE');
  PackageIdentifiers.Add('GMG -- PCG GEOMETRIC MULTI-GRID SOLUTION PACKAGE');
  PackageIdentifiers.Add('HFB -- HORIZONTAL-FLOW BARRIER PACKAGE');
  PackageIdentifiers.Add('HUF2 -- HYDROGEOLOGIC-UNIT FLOW PACKAGE');
  PackageIdentifiers.Add('HYD -- HYDROGRAPH DATA');
  PackageIdentifiers.Add('IBS -- INTERBED STORAGE PACKAGE');
  PackageIdentifiers.Add('LAK7 -- LAKE PACKAGE');
  PackageIdentifiers.Add('LPF -- LAYER-PROPERTY FLOW PACKAGE');
  PackageIdentifiers.Add('MNW1 -- MULTI-NODE WELL 1 PACKAGE');
  PackageIdentifiers.Add('MNW2 -- MULTI-NODE WELL 2 PACKAGE');
  PackageIdentifiers.Add('MNWI Package input');
  PackageIdentifiers.Add('OBS2BAS7 -- HEAD OBSERVATIONS');
  PackageIdentifiers.Add('OBS2CHD7 -- CONSTANT-HEAD BOUNDARY FLOW OBSERVATIONS');
  PackageIdentifiers.Add('OBS2DRN7 -- OBSERVATION PROCESS (DRAIN FLOW OBSERVATIONS)');
  PackageIdentifiers.Add('OBS2GHB7 -- OBSERVATION PROCESS (GHB FLOW OBSERVATIONS)');
  PackageIdentifiers.Add('OBS2RIV7 -- OBSERVATION PROCESS (RIVER FLOW OBSERVATIONS)');
  PackageIdentifiers.Add('OBS2STR7 -- OBSERVATION PROCESS (STREAMFLOW OBSERVATIONS)');
  PackageIdentifiers.Add('PCG -- CONJUGATE-GRADIENT SOLUTION PACKAGE');
  PackageIdentifiers.Add('RCH -- RECHARGE PACKAGE');
  PackageIdentifiers.Add('RES7 -- RESERVOIR PACKAGE');
  PackageIdentifiers.Add('RIV -- RIVER PACKAGE');
  PackageIdentifiers.Add('SFR7 -- STREAMFLOW ROUTING PACKAGE');
  PackageIdentifiers.Add('SIP -- STRONGLY-IMPLICIT PROCEDURE SOLUTION PACKAGE');
  PackageIdentifiers.Add('STR -- STREAM PACKAGE');
  PackageIdentifiers.Add('SUB7 -- SUBSIDENCE PACKAGE');
  PackageIdentifiers.Add('SWT -- SUBSIDENCE FOR WATER-TABLE PACKAGE');
  PackageIdentifiers.Add('UZF1 -- UNSATURATED FLOW PACKAGE');
  PackageIdentifiers.Add('WEL -- WELL PACKAGE');
  PackageIdentifiers.Add('MODFLOW-2005');
end;


Procedure InitializeObsIdentifiers;
begin
  ObsIdentifiers:= TAnsiStringList.Create;
  ObsIdentifiers.Add(StrHEADANDDRAWDOWNOB);
  ObsIdentifiers.Add('CONSTANT HEAD FLOW OBSERVATIONS');
  ObsIdentifiers.Add('DRAIN FLOW OBSERVATIONS');
  ObsIdentifiers.Add('GHB FLOW OBSERVATIONS');
  ObsIdentifiers.Add('RIVER FLOW OBSERVATIONS');
  ObsIdentifiers.Add('STREAMFLOW OBSERVATIONS');
end;

procedure InitializeBoundaryIdentifiers;
begin
  BoundaryIdentifiers := TAnsiStringList.Create;
  BoundaryIdentifiers.Add('REUSING ');
  BoundaryIdentifiers.Add('WELL NO.  LAYER   ROW   COL   STRESS RATE');
  BoundaryIdentifiers.Add('DRAIN NO.  LAYER   ROW   COL     DRAIN EL.  CONDUCTANCE');
  BoundaryIdentifiers.Add('REACH NO.  LAYER   ROW   COL');
  BoundaryIdentifiers.Add('EVTR array defined by the following parameters:');
  BoundaryIdentifiers.Add(' MULT. ARRAY:');
  BoundaryIdentifiers.Add(' HK ');
  BoundaryIdentifiers.Add(' HANI ');
  BoundaryIdentifiers.Add(' SS ');
  BoundaryIdentifiers.Add(' SY ');
  BoundaryIdentifiers.Add(' ETS ');
  BoundaryIdentifiers.Add(' EVT ');
  BoundaryIdentifiers.Add(' RCH ');
  BoundaryIdentifiers.Add('BOUND. NO. LAYER   ROW   COL     STAGE      CONDUCTANCE');
  BoundaryIdentifiers.Add('LAYER   ROW    COL    SEGMENT   REACH');
  BoundaryIdentifiers.Add('CHD NO.   LAYER   ROW   COL    START HEAD        END HEAD');
  BoundaryIdentifiers.Add('STREAM NETWORK DESCRIPTION');
  BoundaryIdentifiers.Add('USING INFILTRATION RATE FROM PREVIOUS STRESS ');
  BoundaryIdentifiers.Add('USING ET RATE FROM PREVIOUS STRESS');
  BoundaryIdentifiers.Add('USING ET EXTINCTION DEPTH FROM PREVIOUS');
  BoundaryIdentifiers.Add('USING EXTINCTION WATER CONTENT FROM PREVIOUS');
  BoundaryIdentifiers.Add('INITIAL LAKE STAGE:  LAKE    STAGE    SS MIN    SS MAX');
  BoundaryIdentifiers.Add('INITIAL LAKE CONCENTRATIONS:  LAKE   CONCENTRATION');
  BoundaryIdentifiers.Add('EVAPOTRANS. RATE (ETSR)');
  BoundaryIdentifiers.Add('EXTINCT. DEP. PROPORTION');
  BoundaryIdentifiers.Add('ET RATE PROPORTION');
  BoundaryIdentifiers.Add('ET LAYER INDEX');
  BoundaryIdentifiers.Add('ET SURFACE');
  BoundaryIdentifiers.Add('EVAPOTRANSPIRATION RATE');
  BoundaryIdentifiers.Add('EXTINCTION DEPTH');
  BoundaryIdentifiers.Add('RECHARGE LAYER INDEX');
  BoundaryIdentifiers.Add('RECHARGE');
  BoundaryIdentifiers.Add('DRAIN NO.  LAYER   ROW   COL     DRAIN EL.  STRESS FACTOR');
  BoundaryIdentifiers.Add('DRAIN NO.  LAYER   ROW   COL   LAYER   ROW   COL    PROP.');
  BoundaryIdentifiers.Add('DRAIN NO.  LAYER   ROW   COL     DRAIN EL.  CONDUCTANCE');
  BoundaryIdentifiers.Add('WELLID             NNODES    LOSSTYPE');
  BoundaryIdentifiers.Add('    No.   Lay   Row   Col    Stress   QW param');
  BoundaryIdentifiers.Add('TOP ELEVATN');
  BoundaryIdentifiers.Add('THICKNESS');
  BoundaryIdentifiers.Add('PARAMETER NAME');
  BoundaryIdentifiers.Add('INTERPRETATION OF UNIT FLAGS:');
  BoundaryIdentifiers.Add('HYD. COND. ALONG ROWS');
  BoundaryIdentifiers.Add('HORIZ. ANI. (COL./ROW)');
  BoundaryIdentifiers.Add('VERTICAL HYD. COND.');
  BoundaryIdentifiers.Add('TOP ELEVATION OF LAYER');
  BoundaryIdentifiers.Add('MODEL LAYER BOTTOM EL.');
  BoundaryIdentifiers.Add('STRESS PERIOD     LENGTH       TIME STEPS     MULTIPLIER FOR DELT    SS FLAG');
  BoundaryIdentifiers.Add('BOUNDARY ARRAY');
  BoundaryIdentifiers.Add('INITIAL HEAD');
  BoundaryIdentifiers.Add('LAYER FLAGS:');
  BoundaryIdentifiers.Add('SPECIFIC YIELD');
  BoundaryIdentifiers.Add('LAYER    ROW    COL   SEGMENT   REACH     LENGTH');
  BoundaryIdentifiers.Add('AREAL EXTENT OF UZ FLOW');
  BoundaryIdentifiers.Add('ROUTING OVERLAND RUNOFF');
  BoundaryIdentifiers.Add('SATURATED VERTICAL K');
  BoundaryIdentifiers.Add('BROOKS-COREY EPSILON');
  BoundaryIdentifiers.Add('SATURATED WATER CONTENT');
  BoundaryIdentifiers.Add('SELECTED MODEL CELLS ARE:');
  BoundaryIdentifiers.Add('SEGMENT    SEG.     INFLOW   OVERLAND   STREAM');
  BoundaryIdentifiers.Add('SEGMENT     BED HYD. COND.      BED THICKNESS');
  BoundaryIdentifiers.Add('EIGHT POINT CROSS-SECTION DATA');
  BoundaryIdentifiers.Add('STREAMFLOW RELATION WITH DEPTH IS BASED ON EQUATION');
  BoundaryIdentifiers.Add('STREAMFLOW RELATION WITH DEPTH AND WIDTH IS BASED');
  BoundaryIdentifiers.Add('AREAL INFILTRATION RATE');
  BoundaryIdentifiers.Add('ET RATE');
  BoundaryIdentifiers.Add('ET EXTINCTION DEPTH');
  BoundaryIdentifiers.Add('EXTINCTION WATER CONTENT');
  BoundaryIdentifiers.Add('MAXIMUM HEAD CHANGE FOR EACH ITERATION');
  BoundaryIdentifiers.Add('WELLS   PERIOD');
  BoundaryIdentifiers.Add('HEAD DEP BOUNDS   PERIOD');
  BoundaryIdentifiers.Add('UNSATURATED ZONE PACKAGE VOLUMETRIC BUDGET');
  BoundaryIdentifiers.Add('STREAM LISTING     PERIOD');
  BoundaryIdentifiers.Add('AT ALL NO-FLOW NODES');
  BoundaryIdentifiers.Add('ZONE ARRAY:');
  BoundaryIdentifiers.Add('INTERPRETATION OF LAYER FLAGS:');
  BoundaryIdentifiers.Add('QUASI3D VERT. HYD. COND.');
  BoundaryIdentifiers.Add('HEAD IN LAYER');
  BoundaryIdentifiers.Add('HEAD AT CELLS THAT CONVERT TO DRY');
  BoundaryIdentifiers.Add('VERT HYD COND /THICKNESS');
  BoundaryIdentifiers.Add('TRANSMIS. ALONG ROWS');
  BoundaryIdentifiers.Add('BARRIER  LAYER  IROW1  ICOL1  IROW2  ICOL2    HYDCHR');
  BoundaryIdentifiers.Add('COLUMN TO ROW ANISOTROPY');
  BoundaryIdentifiers.Add('LAYER  LAYER-TYPE CODE     INTERBLOCK T');
  BoundaryIdentifiers.Add('Run end date and time');
  BoundaryIdentifiers.Add('PRIMARY STORAGE COEF');
  BoundaryIdentifiers.Add('MODEL LAYER ASSIGNMENTS');
  BoundaryIdentifiers.Add('OF DELAY BEDS:');
  BoundaryIdentifiers.Add('OF NO-DELAY BEDS:');
  BoundaryIdentifiers.Add('PRECONSOLIDATION HEAD');
  BoundaryIdentifiers.Add('ELASTIC INTERBED STORAGE');
  BoundaryIdentifiers.Add('VIRGIN INTERBED STORAGE');
  BoundaryIdentifiers.Add('STARTING COMPACTION');
  BoundaryIdentifiers.Add('MATERIAL PROPERTIES OF INTERBEDS');
  BoundaryIdentifiers.Add('DELAY STARTING HEAD');
  BoundaryIdentifiers.Add('DELAY PRECOLSOL. HEAD');
  BoundaryIdentifiers.Add('DELAY INITIAL COMPACTION');
  BoundaryIdentifiers.Add('DELAY INTERBED THICKNESS');
  BoundaryIdentifiers.Add('MATERIAL ZONE INDICES');
  BoundaryIdentifiers.Add('VOLUMETRIC BUDGET FOR SYSTEMS OF DELAY INTERBEDS');
  BoundaryIdentifiers.Add('VOLUMETRIC BUDGET FOR UNSATURATED ZONE');
  BoundaryIdentifiers.Add('DELC');
  BoundaryIdentifiers.Add('DELR');
  BoundaryIdentifiers.Add('STREAMBED PROPERTIES');
  BoundaryIdentifiers.Add('CLASSIFICATION & COUNT OF STREAM SEGMENTS');
  BoundaryIdentifiers.Add('HEAD AT END OF TIME STEP');
  BoundaryIdentifiers.Add('MODEL TIME UNIT');
  BoundaryIdentifiers.Add('MODEL LENGTH UNIT');
  BoundaryIdentifiers.Add('MODEL LAYER ASSIGNMENTS');
  BoundaryIdentifiers.Add('GEOSTATIC STRESS');
  BoundaryIdentifiers.Add('MOIST SPECIFIC GRAVITY');
  BoundaryIdentifiers.Add('SAT. SPECIFIC GRAVITY');
  BoundaryIdentifiers.Add('SILT AND CLAY THICKNESS');
  BoundaryIdentifiers.Add('RECOMPRESSION INDEX');
  BoundaryIdentifiers.Add('COMPRESSION INDEX');
  BoundaryIdentifiers.Add('VOID RATIO');
  BoundaryIdentifiers.Add('STARTING COMPACTION');
  BoundaryIdentifiers.Add('PRECONSOL.   STRESS');
  BoundaryIdentifiers.Add('GEOSTATIC STRESS');
  BoundaryIdentifiers.Add('EFFECTIVE STRESS');
  BoundaryIdentifiers.Add('PRECONSOL STRESS');
  BoundaryIdentifiers.Add('EQUIVALENT Sske');
  BoundaryIdentifiers.Add('EQUIVALENT Sskv');
  BoundaryIdentifiers.Add('SUBSIDENCE IN LAYER');
  BoundaryIdentifiers.Add('LAYER COMPACTION IN LAYER');
  BoundaryIdentifiers.Add('CHANGE IN PCSTRS IN LAYER');
  BoundaryIdentifiers.Add('CHANGE IN G-STRS IN LAYER');
  BoundaryIdentifiers.Add('CHANGE IN EFF-ST IN LAYER');
  BoundaryIdentifiers.Add('STREAM SEGMENT               TRIBUTARY STREAM SEGMENT');
  BoundaryIdentifiers.Add('DIVERSION SEGMENT NUMBER          UPSTREAM SEGMENT NUMBER');
  BoundaryIdentifiers.Add('LAYER      ROW     COLUMN     STREAM');
  BoundaryIdentifiers.Add('SECONDARY STORAGE COEF');
  BoundaryIdentifiers.Add('WETDRY PARAMETER');
  BoundaryIdentifiers.Add('RESERVOIR LOCATION');
  BoundaryIdentifiers.Add('RESERVOIR LAND SURF ELEV');
  BoundaryIdentifiers.Add('RES. BED VERT HYD COND');
  BoundaryIdentifiers.Add('RESERVOIR BED THICKNESS');
  BoundaryIdentifiers.Add('STAGE-VOLUME TABLE FOR RESERVOIR');
  BoundaryIdentifiers.Add('RESERVOIR CONDITIONS FOR STRESS PERIOD');
  BoundaryIdentifiers.Add('MNW2 Well Conductance and Screen');
  BoundaryIdentifiers.Add('Entry LAY ROW COL         Q');
  BoundaryIdentifiers.Add('Multi-Node Rates & Average QW');
  BoundaryIdentifiers.Add('LAYER  ROW  COL IAUX');
  BoundaryIdentifiers.Add('LAKE ID ARRAY');
  BoundaryIdentifiers.Add('LAKEBED LEAKANCE ARRAY');
  BoundaryIdentifiers.Add('LOCATIONS, LAKE #');
  BoundaryIdentifiers.Add('STAGE/VOLUME RELATION');
  BoundaryIdentifiers.Add('NUMBER OF CONNECTED');
  BoundaryIdentifiers.Add('LAKE       PRECIP     EVAP');
  BoundaryIdentifiers.Add('INTERFACE CONDUCTANCES BETWEEN LAKE AND AQUIFER CELLS');
  BoundaryIdentifiers.Add('HYDROLOGIC BUDGET SUMMARIES');
  BoundaryIdentifiers.Add('CUMULATIVE HYDROLOGIC BUDGET SUMMARIES');
  BoundaryIdentifiers.Add('TIMES FOR SPECIFYING FLOWS AND HEADS');
  BoundaryIdentifiers.Add('INFORMATION ON PARAMETERS LISTED IN PARAMETER FILE');
  BoundaryIdentifiers.Add('MAXIMUM RESIDUAL FOR EACH ITERATION');
  BoundaryIdentifiers.Add('BOT. EL. OF QUASI-3D BED');
  BoundaryIdentifiers.Add('HORIZ. TO VERTICAL ANI.');
  BoundaryIdentifiers.Add('SPECIFIC STORAGE');
  BoundaryIdentifiers.Add('STORAGE COEFFICIENT');
  BoundaryIdentifiers.Add('RESERVOIR LAYER INDEX');
  BoundaryIdentifiers.Add('ELASTIC SPECIFIC STORAGE');
  BoundaryIdentifiers.Add('INELAS. SPECIFIC STORAGE');
  BoundaryIdentifiers.Add('ELEV. OF LAYER CENTER');
  BoundaryIdentifiers.Add('ELEV. OF LAND SURFACE');
  BoundaryIdentifiers.Add('CENTER ELEVATION');
  BoundaryIdentifiers.Add('EQUIVALENT Cr');
  BoundaryIdentifiers.Add('EQUIVALENT Cc');
  BoundaryIdentifiers.Add('INITIAL WATER CONTENT');
  BoundaryIdentifiers.Add('UZ CELL BOTTOM ELEV.');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
//  BoundaryIdentifiers.Add('aaa');
end;

initialization
  InitializePackageIdentifiers;
  InitializeObsIdentifiers;
  InitializeBoundaryIdentifiers;

finalization;
  PackageIdentifiers.Free;
  ObsIdentifiers.Free;
  BoundaryIdentifiers.Free;

end.
